// Production defaults for the static Cloudflare deployment. The local nginx
// container replaces this file at startup using its Compose environment.
window.SovereignRuntimeConfig = Object.freeze({
  environment: 'production',
  services: Object.freeze({
    website: 'https://demo.sovereign.ngo/',
    app: 'https://demo.sovereign.ngo/',
    pods: 'https://pods.demo.sovereign.ngo/',
    organizations: Object.freeze({
      united_states_passport_office: 'https://passport.api.demo.sovereign.ngo/',
      state_driver_licensing_agency: 'https://driver-license.api.demo.sovereign.ngo/',
      nolichucky_family_clinic: 'https://nolichucky.api.demo.sovereign.ngo/',
      riverbend_dental_clinic: 'https://riverbend.api.demo.sovereign.ngo/',
      riverstone_radiology_center: 'https://riverstone-radiology-center.api.demo.sovereign.ngo/',
      summitview_emergency_department: 'https://summitview-emergency-department.api.demo.sovereign.ngo/',
      fairmannor_house: 'https://fairmannor-house.api.demo.sovereign.ngo/',
      safeharbor_shelter: 'https://safeharbor-shelter.api.demo.sovereign.ngo/',
      community_food_pantry: 'https://community-food-pantry.api.demo.sovereign.ngo/',
      bridgeway_family_services: 'https://bridgeway-family-services.api.demo.sovereign.ngo/',
      family_mediation_center: 'https://family-mediation-center.api.demo.sovereign.ngo/',
      salutation_army: 'https://salutation-army.api.demo.sovereign.ngo/',
      pioneer_legal_benefits_navigation: 'https://pioneer-legal-benefits-navigation.api.demo.sovereign.ngo/',
      tenant_rights_advocacy_network: 'https://tenant-rights-advocacy-network.api.demo.sovereign.ngo/',
      community_legal_family_support: 'https://community-legal-family-support.api.demo.sovereign.ngo/',
      financial_wellness_center: 'https://financial-wellness-center.api.demo.sovereign.ngo/',
      community_tax_services: 'https://community-tax-services.api.demo.sovereign.ngo/',
      consumer_regulation_support: 'https://consumer-regulation-support.api.demo.sovereign.ngo/',
      commonwealth_credit_union: 'https://commonwealth-credit-union.api.demo.sovereign.ngo/',
      neighborhood_insurance_brokers: 'https://neighborhood-insurance-brokers.api.demo.sovereign.ngo/',
      valley_notary_office: 'https://valley-notary-office.api.demo.sovereign.ngo/',
      community_legal_aid_collective: 'https://community-legal-aid-collective.api.demo.sovereign.ngo/',
      ascent_employment_placement_agency: 'https://ascent-employment-placement-agency.api.demo.sovereign.ngo/',
      rapid_response_temporary_help: 'https://rapid-response-temporary-help.api.demo.sovereign.ngo/',
      cedar_document_preparation_center: 'https://cedar-document-preparation-center.api.demo.sovereign.ngo/',
      brightpath_educational_support_center: 'https://brightpath-educational-support-center.api.demo.sovereign.ngo/',
      ridgeview_behavioral_health_center: 'https://ridgeview-behavioral-health-center.api.demo.sovereign.ngo/',
      bluepeak_medical_laboratory: 'https://bluepeak-medical-laboratory.api.demo.sovereign.ngo/',
      caringhands_home_health: 'https://caringhands-home-health.api.demo.sovereign.ngo/',
      tri_county_ambulance: 'https://tri-county-ambulance.api.demo.sovereign.ngo/',
      foothills_disability_support_services: 'https://foothills-disability-support-services.api.demo.sovereign.ngo/',
      pathway_vocational_rehabilitation: 'https://pathway-vocational-rehabilitation.api.demo.sovereign.ngo/',
      dignity_human_rights_organization: 'https://dignity-human-rights-organization.api.demo.sovereign.ngo/',
      appalachian_electric_distribution: 'https://appalachian-electric-distribution.api.demo.sovereign.ngo/',
      holston_wireless_carrier: 'https://holston-wireless-carrier.api.demo.sovereign.ngo/',
      blue_river_natural_gas_utility: 'https://blue-river-natural-gas-utility.api.demo.sovereign.ngo/',
      volunteer_electrical_contractors: 'https://volunteer-electrical-contractors.api.demo.sovereign.ngo/',
      foothills_plumbing_hvac_contractors: 'https://foothills-plumbing-hvac-contractors.api.demo.sovereign.ngo/',
      clearwater_public_water_utility: 'https://clearwater-public-water-utility.api.demo.sovereign.ngo/',
      mainstreet_community_pharmacy: 'https://mainstreet-community-pharmacy.api.demo.sovereign.ngo/',
      homestead_residential_leasing: 'https://homestead-residential-leasing.api.demo.sovereign.ngo/',
      cornerstone_property_management: 'https://cornerstone-property-management.api.demo.sovereign.ngo/',
      summit_health_insurance_carrier: 'https://summit-health-insurance-carrier.api.demo.sovereign.ngo/',
      atlas_claims_administration: 'https://atlas-claims-administration.api.demo.sovereign.ngo/',
      sunrise_child_day_center: 'https://sunrise-child-day-center.api.demo.sovereign.ngo/',
      youthpath_child_services: 'https://youthpath-child-services.api.demo.sovereign.ngo/',
      beacon_emergency_relief_services: 'https://beacon-emergency-relief-services.api.demo.sovereign.ngo/',
      horizon_residential_recovery_center: 'https://horizon-residential-recovery-center.api.demo.sovereign.ngo/',
      highland_workforce_training_institute: 'https://highland-workforce-training-institute.api.demo.sovereign.ngo/'
    })
  })
});
